WeMakeDevs/wemakedevs

src/components/About.js
src/components/Blog.js
src/components/Courses.js
src/components/Footer.js
src/components/Founder.js
src/components/Header.js
src/components/Mentorship.js
src/components/Podcast.js
src/styles/Courses.css
src/styles/Event.css

[FIX]: Alt fix

---

.github/workflows/greetings.yaml

Greets users on creating their new issue/PR in this repo
Closes #15

Added greetings action

---

src/components/About.js
src/components/Blog.js
src/components/Mentorship.js
src/components/Podcast.js
src/components/navbar/Navbar.js

- Added the roadmap repo link
- Changed the discord link to the custom invite link
- Podcast will now redirect to the OSC playlist
- [ x ] My code follows the code style of this project.
- [ x ] All new and existing tests passed.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.

Added important links

---

package-lock.json
package.json
src/components/Podcast.js
src/pages/HomePage.js
src/styles/Blog.css
src/styles/Founder.css
src/styles/Header.css
src/styles/Podcast.css
src/styles/navbar.css

closes #71 
-> Header Responsive
-> Podcast Responsive
-> Founder Responsive

[Other] <Responsiveness>

---

src/App.js

[Bug]<Fixed>

---

public/404.html
public/index.html
src/App.js

issue#79 resolved

---

src/components/Event/Events.css

[FIX]: Events Responsiveness

---

src/components/Course/Course.js
src/components/Course/course.css

[FIX]: Course Page

---

src/components/Course/Card.js
src/components/Course/CardsList.js
src/components/Course/Course.js
src/components/Course/Header.js
src/components/Course/data.js
src/components/Event/Card.js
src/components/Event/CardsList.js
src/components/Event/Events.js
src/components/Event/Header.js
src/components/Event/data.js

closes #103 
- Made reusable components and extracted data to make it reusable and easily modifiable

refactor: made Event and Course reusable and easily modifiable.

---

src/components/Course/Card.js
src/components/Course/data.js
src/components/Event/Card.js
src/components/Event/data.js
src/pages/Hashnode.js

closes #107 
- Ongoing event card redirects to the respective link
- Courses card redirects to the respective courses link.

[fix] Events and courses cards don't redirect to their respective link

---

.gitpod.yml

Adds the configurations of Gitpod
<a href="https://gitpod.io/#https://github.com/commclassroom/commclassroom/pull/119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gitpod config

---

src/components/Course/course.css
src/components/Event/Card.js
src/components/Hashnode/Hashnode.css
src/components/Hashnode/Participate.js
src/components/Podcast.js
src/components/Roadmap/Header.js

[Fix]: Hashnode page

---

src/components/Hashnode/Header.js

Fixes a grammatical error found on the hashnode blogging challenges page.
Changed "We will be provide resources." to "We will be providing resources."

Fixed a typo found on the hashnode page.

---

src/components/Courses.js
src/components/Event.js
src/components/Mentorship.js

Fixed the routing errors in the homepage components
Fixes #134

Hotfix: Fixed routing bugs in homepage components

---

src/styles/Header.css

No cursor pointer on the header button.
closes #116 
Added cursor: pointer property to Header.css file.
- ### Before
- ### After

No cursor pointer fixed #116

---

src/styles/Founder.css
src/styles/Header.css

closes #146 
A simple looking infinite gradient animation on the gradient texts
https://user-images.githubusercontent.com/68517592/203653417-aa7f2e25-2040-4311-af5a-33f3b56750af.mp4

added animation to the gradients on home page

---

src/v2/components/home/about/index.jsx
src/v2/components/home/about/index.module.css
src/v2/components/home/courses/index.module.css
src/v2/components/home/events/index.module.css
src/v2/components/home/roadmaps/index.module.css

[Fix]: Home Page

---

src/v1/components/common/navbar/data.js
src/v1/components/common/navbar/index.jsx

- `Before` : Clicking on `home` button was opening a new tab of `WeMakeDevs` website
- `After` : Clicking on `home` button no longer opens a new tab
closes #154 
- Modified `data.js` and made home link external false
- Refactored `navlinks.map()` and implemented conditional rendering for external links

Bug-Fix: External link opening while clicking home

---

src/v2/components/common/footer/index.jsx

[FIX]: Footer

---

src/v2/components/common/navbar/index.jsx

[FIX]: Icons

---

src/v2/components/common/footer/index.jsx

Fixed wrong redirecting links of buttons.

---

src/v2/components/common/navbar/data.js
src/v2/components/common/navbar/index.jsx

- Clicking Home does not reloads the page
closes #171 
- Modified Navbar data in V2
- Enabled Conditional rendering for nav links
N/A

Fix-Bug: Opening same domain again and again in V2

---

src/v2/components/common/navbar/index.jsx

The PR #182 reimported `Link` of `react-router-dom`, resulting in continuous failure of build process. This PR removed that duplicate import.

fix reclaration in issue in pr #182

---

.github/workflows/labeler.yaml

The labeler action has been updated as ownership has been transferred to the WeMakeDevs org.

update labeler-action to wemakedevs

---

.github/workflows/labeler.yaml

update labeler-action version

---

src/components/layout/Footer/index.jsx

Added telegram group and discord server links in footer banner

Community links added in footer banner

---

.github/workflows/labeler.yaml

Change labeler action version from v1 to v1.3.0

fix labeler-action version issue

---

src/components/home/events/index.jsx

Fixed ID of Event component

---

src/components/Accordion/Accordion.jsx
src/components/Accordion/AccordionItem.jsx
src/components/Accordion/index.css
src/components/home/FAQ/data.js
src/components/home/FAQ/index.jsx
src/components/home/FAQ/index.module.css
src/components/home/Stats/index.jsx
src/components/home/Stats/index.module.css
src/pages/HomePage.jsx

closes #244 
- The stats section will display the statistics of this community
- The FAQ section will answer the commonly asked questions

feat: stats, FAQ section

---

.github/workflows/labeler.yaml

A few changes are made to the labeler action to deal with integration access problem and version has been upgraded to get it working as expected.

update the labeler action

---

src/App.jsx
src/pages/ErrorPage/index.jsx
src/pages/ErrorPage/index.module.css

If a user navigates to a unknown routes an `Error Page` will pop up now instead of a blank page. In the error page there will be a `Back to Home`  button, by clicking it user will navigate to `Home Page`
- Added a route with * path which will automatically handle unknown/random routes that are now listed.
- Added a Error Page that will pop up on unknown route
- Added some CSS to the Error Page
- Added functionality to the Back to Home button
- Here comes all the changes proposed through this PR
closes #192 
As the project has moved to a new code base. There was lots of merging issues. That's why I refactored and reopen the pull request, There's no …

Bug-Fix: Handle unknown routes or 404 not found page

---

.github/workflows/greetings.yaml

The pull_request event in the greetings action is changed to pull_request_target to deal with failure in runtime. Event types has also been modified to opened only.

fix greeting action failure

---

src/components/home/about/index.module.css
src/components/layout/Header/index.module.css

Before:
https://user-images.githubusercontent.com/67385503/209458849-f4d9b53e-5252-45df-812e-73c10f8570b4.mp4
Now:
https://user-images.githubusercontent.com/67385503/209458870-b403ca3f-ba70-41dc-9bc1-50092aba8d36.mp4

Updated CSS for Boxes (Education, Events & Mentorship) from 768px to 870px 

---

src/components/layout/Header/index.module.css

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>
Before:
Now:
closes #issue-number 

Added margin to Navbar from Top

---

.husky/post-merge
src/components/Accordion/index.css
src/components/home/FAQ/index.module.css
src/components/home/Partner/index.module.css
src/components/home/Stats/index.module.css
src/components/home/Testimonial/index.module.css
src/components/layout/ColumnSection/index.module.css

fixed inconsistent spacing between heading  and content

---

src/components/home/Stats/index.jsx

This PR fixes the following issues: 
Updated the stats as requested in issue #261 
closes #261 
-- Changed 55,000 members to 56,000 members.

Updated the members stat.

---

src/components/home/FAQ/index.jsx
src/components/home/Testimonial/index.jsx
src/components/layout/Footer/index.jsx
src/components/layout/Footer/index.module.css

closes #272 
Add category-wise links:
- Organization
- About
- Testimonials
- FAQ 
- Community
- Blog
- Events
- Courses
- Mentorship
- Newsletter
- Socials 
- Instagram
- Linkedin
- Twitter 
- GitHub
- Youtube
- Contact
- kunal@wemakedevs.org
- Discord
- Telegram

feat: footer with category links

---

src/components/home/Testimonial/index.jsx

Fixed a typo in one of the testimonials.
closes #257 
-- Fixed typo from "conecpt" to "concept"

Fixed Typo in testimonials

---

src/components/home/Testimonial/index.module.css

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>
closes #issue-number #279
Before:
Now:
https://user-images.githubusercontent.com/67385503/209480074-b7415e9a-45af-4b4e-8907-037c7fe9c1c2.mp4

Responsiveness of Testimonial Boxes

---

src/components/layout/ColumnSection/index.module.css

Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>
closes #256 
https://user-images.githubusercontent.com/67385503/209479851-1d9374e2-f6a6-4e9c-a895-0ccadff045c1.mp4

Updated CSS (margin in the button)

---

src/components/home/JoinUs/index.jsx

closes #259
The members count is 56k it was 56 only

Fixed incorrect data

---

src/components/home/about/cards.jsx

updated content and fixed conflicts

---

src/components/home/Blogs/index.jsx
src/components/home/about/cards.jsx

Added content in blog section and updated links
closes #NA

Added content in blog section and updated links

---

src/components/Button/index.module.css
src/components/home/NewsLetter/index.jsx
src/components/home/NewsLetter/index.module.css
src/components/home/index.js
src/components/links/ButtonLink/index.module.css
src/pages/HomePage.jsx

Add the Newsletter section using Iframe

feat: Newsletter section

---

.github/workflows/codeql.yml
.github/workflows/node.js.yml

Added the CodeQL workflow to perform security scans and NodeJS workflow to check if the code in new PRs build without an error.

Add codeql and nodejs actions

---

.github/workflows/greetings.yaml

closes #305 
Replaced EddieHubCommunity/gh-action-community/src/welcome@main by actions/first-interaction@v1 to stop greeting those who have already contributed. Issue creators will continue receiving messages irrespective of prior contributions though.

update greetings action to greet first-timers only

---

.github/workflows/greetings.yaml

The GitHub-token has been changed to repo-token as per the need to the actions/first-interaction@v1

fix greetings action failure

---

src/components/home/JoinUs/index.jsx
src/components/home/Mentorship/index.jsx
src/components/home/NewsLetter/index.jsx
src/components/home/Podcast/index.jsx
src/components/home/courses/index.jsx
src/components/home/events/index.jsx
src/components/layout/Backdrop/index.jsx
src/components/layout/Footer/index.jsx
src/components/layout/Footer/index.module.css
src/components/layout/Header/index.jsx
src/components/layout/Header/index.module.css
src/components/links/UnstyledLink.jsx
src/pages/HomePage.jsx

closes #283 #255 #246 #206 
- Mobile Navigation Link will not be visible on Laptop
File Changed `src\components\layout\Header` `src\components\layout\index.module.css`
- Fix the ID for the Sections of home page
File Changed: `src\components\home` -> `courses`, `events`, `JoinUs`, `Mentorship`, `Newsletter`, `Podcast` 
- In Mobile View Scroll be not locked
File Changed: `src\components\layout\Header` 
- Changed `a` with `UnstyledLink` in footer and footer width 100%
File Changed `src\components\layout\Footer` `src\components\layout\Footer\index.module.css`

fix: UI, Navbar and Section

---

src/components/home/JoinUs/index.jsx
src/components/home/NewsLetter/index.jsx
src/components/home/Stats/index.jsx
src/components/home/Work/index.jsx

Made the heading of the homepage sentence case from the title case

fix: made the heading sentence-case

---

src/components/home/JoinUs/index.jsx
src/components/home/JoinUs/index.module.css

- removed NewsLetter card
- Color change in card

refactor: removed the newsletter from join Us section

---

src/pages/HomePage.jsx

removed cards in about us section

removed cards in about us section

---

src/components/home/header/index.jsx

Added one mentorship button in header section

[Feature]: Add one mentorship button

---

src/assets/home/Cisco.svg
src/assets/home/RedBus.svg
src/assets/home/Samsung.svg
src/assets/home/adobe.svg
src/assets/home/amazon.svg
src/assets/home/google.svg
src/assets/home/microsoft.svg
src/assets/home/razorpay.svg
src/assets/home/virtusa.svg

There was a bug that in safari images were not visible but with the latest changes, it is visible in Safari as well.

[FIX]: Safari Images

---

src/components/home/Content/index.jsx
src/components/home/Content/index.module.css
src/components/home/JoinUs/index.jsx
src/components/home/JoinUs/index.module.css
src/components/home/Mentorship/index.jsx
src/components/home/NewsLetter/index.jsx
src/components/home/Partner/index.jsx
src/components/home/about/index.jsx
src/components/home/courses/index.jsx
src/components/home/header/index.jsx
src/components/layout/ColumnSection/index.module.css
src/components/layout/Footer/index.jsx
src/components/layout/Header/index.jsx
src/components/links/ButtonLink/index.module.css
src/pages/HomePage.jsx

[x] change newsletter button to Partner with us - 
[x] change the text of header CTAs to -> Courses, Mentorship, Events (remove Visit, see words)
[x] Redirect Header CTAs to GitHub Repos
[x] In About us, add 3 buttons: Discord, Telegram, and Newsletter(scroll to the newsletter section)
[x] Courses section, even spacing above and below $0/month
[x] All buttons should be sentence case - 
[x] In the content section, add padding to the cards
[x] In the content section, keep buttons as above sections - rounded with an arrow icon
[x] In Join us, change the text in the telegram button "Stay up-to-date with news and announcements"
preview: https://wemakedevs.vercel.app/

style: ui update

---

src/components/home/FAQ/data.js
src/components/layout/Banner/index.jsx
src/components/layout/Banner/index.module.css

Added cross mark in banner and updated FAQs

Added cross mark in banner and updated FAQs

---

src/components/home/header/index.jsx

closes #337 
- Courses CTA link redirect to [youtube link](https://www.youtube.com/@KunalKushwaha/playlists?view=50&sort=dd&shelf_id=3)

fix: courses CTA link

---

src/components/home/FAQ/data.js

closes #331 
Changed the FAQ data.

fix: FAQ data

---

src/components/home/NewsLetter/index.jsx

closes #330 
- Made the newsletter iframe responsive

fix: newsletter iframe responsive

---

package-lock.json
package.json
src/components/home/events/index.jsx

closes #332
Add the twitter widget package 
Used carsoul package to create tweet layout

feat: Prize Tweet

---

src/components/home/Content/index.jsx
src/components/home/courses/index.jsx
src/components/layout/Header/index.jsx

fix: small changes

---

src/components/home/Testimonial/data.js

Fix the data in courses testimonials

fix: course testimonial data

---

src/components/home/PartnerTestimonials/index.module.css
src/components/home/Testimonial/index.module.css

closes #349 
- same height of all testimonial cards

style: same height of testimonial cards

---

src/components/eventspage/about/index.jsx
src/components/eventspage/tracks/data.js

removed archived battlesnake repo link from events Card.

---

src/components/eventspage/about/index.jsx
src/components/eventspage/prizes/index.jsx
src/components/eventspage/tracks/index.jsx
src/pages/content.js

Events, Ongoing, Past, Join
Fixed the links in navbar not working - add id to sections. Events, Ongoing, Past, Join.

added id sections in events page

---

src/components/eventspage/stats/index.jsx

closes #379 
Here comes all the changes proposed through this PR:
Changed the icons in the eventspage, stats section.

Change icons in eventspage

---

src/components/layout/Banner/index.module.css

closes #384
- Font size changed from `1.1rem` to `1.05rem` at screen size `768px`

[bug] Cancel icon should be in a row

---

src/components/hashnode/offer/index.jsx

tpyo fix in hashnode/offer/index.jsx

typo fix in hashnode/offer/index.jsx

---

src/components/eventspage/shoutout/index.jsx
src/components/eventspage/stats/index.jsx
src/components/hashnode/offer/index.jsx
src/pages/content.js

fix: review changes done

---

src/components/SingleCoursePage/About/index.module.css
src/components/SingleCoursePage/syllabus/index.module.css
src/components/coursespage/Hero/index.jsx
src/components/eventspage/Hero/index.jsx
src/components/eventspage/about/index.jsx
src/components/layout/Banner/index.jsx
src/components/layout/Banner/index.module.css
src/components/layout/Partner/index.jsx
src/content/devops.js
src/content/dsa.js

- Banner styles
- Content in courses page
- syllabus in grid pattern

Review-fix

---

README.md

Links are added to respective logos. Changes are made to README.md file
In README.md file there is no any link associated to respective logos due to which navigation to the site by clicking those logos where not possible.
closes #419 

Respective links are added to respective logos.

---

src/pages/content.js

fixes no issue , provides with a typo-fix

typo-fix in src/pages/content.js

---

src/components/coursespage/Testimonial/index.jsx
src/components/layout/Testimonials/index.jsx
src/content/gitGithub.js

Updated Syllabus of courses

---

README.md

#408
#408 
Centered the counts and title

Changed Position of Title 'wemakedevs '

---

README.md

make necessary changes for icon to be aligned.

---

src/components/layout/Banner/index.module.css

closes #439
- Removed the `flex-wrap` property for the small screen.
- Added the `flex-shrink` property to the icon.

[bug] Upcoming Events Banner Responsiveness Fixed

---

src/components/layout/Navbar/index.jsx

Fixes issue #373: Clicking the logo doesn't navigate to the top of the page #373 
closes #373 
changed **src/components/layout/Navbar/index.jsx** file

Solved: Clicking the logo doesn't navigate to the top of the page #373

---

src/components/links/UnstyledLink.jsx
src/styles/root.css

This PR fixes the following issues: 
It removes a feature that does not work in a few places and confuses the user to be a bug
closes #450 
- removed a new-tab class from root.css as suggested by @Chandraprakash-Darji

Fixes #450

---

src/components/SingleCoursePage/syllabus/index.jsx

Added an id of name 'syllabus' at line number 7 which helps to redirect from the navbar's link 'Syllabus' to the syllabus section. Path - src\components\SingleCoursePage\syllabus\index.jsx 
If I did anything incorrectly, please suggest/guide me as if it is my very first contribution to an Open Source project. 
Thanks!
fixes issue that - In Git-Github course page, when the user clicks on the navigation link 'Syllabus', it does not redirect to the syllabus section.
This PR fixes the issues - now, the user can redirect to the syllabus section by clicking the navigation link 'Syllabus' on Git-Github course page.
- [ ✅] My code follows the code style of this project.
- [ ✅] My change …

Updated index.jsx file

---

src/components/layout/Footer/index.module.css

Footer Padding
closes #452
Decreased the footer padding from 10rem to 6rem

Fixes Footer Padding

---

package-lock.json
package.json
src/components/home/Stats/index.jsx
src/components/home/Stats/index.module.css
src/components/layout/Footer/index.module.css

This PR adds a new feature Animating Counter Up stats 
closes #339
Added a new feature which animates counter up in the about section on scroll
- [ x ] My code follows the code style of this project.
- [ x ] All new and existing tests passed.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.
https://user-images.githubusercontent.com/63769209/221009556-a9686cb5-ef6d-4c10-96c4-9cd93498623e.mp4

[Feat] Animating Counter Up Stats

---

README.md

- The missing step during installation has been added. 
-  Unnecessary spaces have been removed
- The installation process missed the step of changing the directory after cloning the repository to execute 'npm i'
- This pull request resolves the issue by removing unnecessary spaces and ensuring there are no spaces after the backtick.

updated Readme.md Installation step

---

src/pages/ErrorPage/index.jsx
src/pages/ErrorPage/index.module.css

closes #462
1. Fixed the bug on the not found page where 404! and the sentence below it is attached together in the mobile view.
2. Changed the background color of the Back To Home button so it appears clearly as a button.

Fixed the bug on Not Found Page

---

README.md

- Converted all the "commclassroom" links to "wemakedevs".

Converted all the "commclassroom" links to "wemakedevs"

---

src/components/layout/Partner/index.module.css

closes #438 
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.

Fixed the bug "Responsive for mobile screen" #438 (Error where Partner with us button was wrapping)

---

src/components/layout/NewsLetter/index.module.css

- #466 
1) Changed from padding-block to padding-top in components->layout->NewsLetter->index.module.css . This affects the bottom padding for not being to much.

Reduce bottom padding in Subscribe to Our Newsletter

---

src/components/hashnode/Announcement/index.jsx

closes #475 
- Previously, the progress bar is for the number of students mentored
- Now the progress bar indicates 1 month of the 4-month challenge completed

fix: hashnode progress bar

---

src/components/home/Content/index.jsx

closes #493 
- Fixes the podcast link on the home page

fix: podcast link

---

src/components/layout/Footer/index.module.css

Enabling Hover Effects on Footer Icons #496
closes #issue-number #496
The proposed implementation involves adding CSS styles for hover effects on the footer icons. The implementation should be done in a way that is compatible with different browsers and devices. And the color is in line with the primary color being used currently on the website.

Enabling Hover Effects on Footer Icons

---

src/content/Hackathons/index.js

Changed the FAQs for the nappative hackathon!!

fix: change faqs for napptive hackathon

---

src/components/Cards/TimeLineCard.jsx
src/content/Hackathons/napptive.js
src/pages/PerticularhackathonPage.jsx

fix: Hackathon Page

---

src/content/Hackathons/napptive.js

Submission form link for the napptive hackathon has been added.

feat: add submission form for hackathon

---

src/components/PageComp/HashnodePage/Tracks.jsx

closes #512 
https://user-images.githubusercontent.com/92678867/229306502-1c20be2f-d55d-42d1-9361-0679f28179e6.mp4

fixed navbar Tracks link

---

src/pages/PerticularhackathonPage.jsx

#520 
I have deleted repeated text under the issue that was mentioned #520 
- [X ] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

Remove unnecessary repetition from Napptive Hackathon page

---

src/content/Hackathons/napptive.js

fix: hackathon end time

---

src/components/layout/Banner.jsx

changed the banner content to Napptive hackathon

fix: banner content to hackathon

---

src/components/PageComp/HomePage/Events.jsx

This PR fixes the following issue:
fixes the Home page in #525 
This PR removes 3 buttons from [here](https://wemakedevs.org/#events) and replaces it with one button `Ongoing events` that points to the [Events page](wemakedevs.org/events).

update: replace the 3 buttons in the Events menu on the Home page with 1 button

---

README.md

Added html link to wemakedevs image which directs towards wemakedevs official website in a new tab.

Added html link to wemakedevs image

---

src/pages/PerticularhackathonPage.jsx

key value was not passed properly in hackathon page.
closes #issue-number #541
I just changed the value passed to key.
This was the error:-
After fixing:-

issue #541 fixed (key prop is working properly)

---

src/components/Cards/MeetupCard.jsx
src/components/Cards/SpeakerCard.jsx
src/content/Meetup/delhi-2023.js

Changed few things in delhi meetup page

fix: meetup changes

---

src/styles/tailwind.css

Adds smooth transition animation when the site is navigated using the links/buttons in the navbar.
This PR fixes the following issues: Then site has no smooth scrolling transition when navigated using the links/buttons in the navbar, it was missing scroll-behaviour: smooth in the html.
closes #547
Adds scroll-behaviour: smooth in html in the tailwind.css file of the styles folder of the src.
https://user-images.githubusercontent.com/69980616/231408737-ae69112f-b46d-4936-ab67-6e839052278b.mp4
https://user-images.githubusercontent.com/69980616/231410885-326424a3-1e59-47ce-9a6b-4f8e2f54f677.mp4

Adds smooth transition.

---

src/components/PageComp/HomePage/Work.jsx

Solved: Redesigned work section #539

---

src/content/Meetup/delhi-2023.js

Fix community manager typo

---

src/components/PageComp/HomePage/Events.jsx

closes #552
Changed **Testimonials** to **Events Winners** to avoid confusion.

fix: Removed duplicate Testimonials section

---

src/components/PageComp/EventsPage/OngoingEvents.jsx
src/components/PageComp/EventsPage/PastEvents.jsx
src/components/layout/Banner.jsx

Updated the content of events page - Placed the napptive hackathon in past events
Updated the banner because registrations have been closed for the meetup.

fix: events page

---

src/content/super25.js
src/pages/Super25Page.jsx

Add New FAQ and delete unwanted text

---

src/components/PageComp/EventsPage/About.jsx
src/components/PageComp/HashnodePage/HowTakePart.jsx
src/components/PageComp/HomePage/Events.jsx
src/components/TweetCarousael/index.jsx
src/components/layout/Testimonials.jsx
src/pages/CoursesPage.jsx
src/pages/SingleCoursePage.jsx

Fixed Layout if no Tweet Available

---

README.md

Here comes all the changes proposed through this PR:
**Upgraded the existed social icons which were barely visible in other themes / were not looking good**
**Before** 👇
**After** 👇

upgraded social icons

---

src/components/layout/Banner.jsx

- Changed to check out our upcoming Super25 program

feat: super25 banner

---

src/content/Meetup/delhi-2023.js
src/pages/Super25Page.jsx

fixed the cursor:pointer issue in the super25 page
closes #597 
removed the cursor:pointer attribute from the list elements

fixed cursor:pointer issue

---

src/content/super25.js

It fixes some spelling mistakes (stipend and referral) that were done in super 25 faq section
closes #600 
I have fixed some spelling mistakes in super 25 faq section (file => content/super25.js)
I have proposed to change the incorrect spellings in super 25 faq section

fixed some spellings on super 25 faq section

---

public/index.html
src/content/Meetup/delhi-2023.js

Fixes #605 
Added Opengraph meta tags to make the post have an image, website link and a title when shared. Added meta tags for twitter also!!
Screenshots can be taken when we get a hosted link that can be pasted in card validators like:
1. [LikedIn card validator](https://www.linkedin.com/post-inspector/)
2. [Twitter Card Validator](https://tweetpik.com/twitter-card-validator)

perf: add metatags

---

src/components/PageComp/HomePage/Work.jsx

Fixes #603 
"Our Students work at" text color is now fixed for light browser theme

fix: text-color in work.jsx

---

src/components/PageComp/HomePage/Testimonials.jsx
src/components/TweetCarousael/index.jsx
src/components/layout/Partner/PartnerTestimonials.jsx

I refactored the styling and adjusted the spacing of the side arrows in the carousel component. The changes made improve the visual appearance and ensure a more consistent user experience.
closes #607 
Previously, the side arrows in the carousel had a default color and spacing that didn't align with the overall design aesthetic of the content. Recognizing the importance of consistency and cohesiveness in user interfaces, this commit addresses these concerns and brings significant improvements to the component's appearance.

Refactor carousel side arrows styling and spacing in content

---

src/components/layout/Banner.jsx

Updated lower banner from super25 to events

Updated lower banner from super25 to events

---

src/components/PageComp/HackathonsPage/PastEvents.jsx

Change ‘Know more’ to ‘Learn more’
of three in hackathon in hackathon page

Updated ‘Know more’ to ‘Learn more’ in hackathon page

---

src/components/PageComp/EventsPage/EventCategories.jsx

Changed Hashnode event title in card to “Blogging challenges”

Changed Hashnode event title in card to “Blogging challenges”

---

src/components/PageComp/EventsPage/Stats.jsx

Resolves #630 
- $20,000+ prizes
- 30,000+ participants
- 30+ countries
- 200,000+ empowered

Changed numbers

---

src/components/layout/JoinUs/index.jsx

closes #642 
- fixed the discord and telegram card
- added gap between join us section and newsletter section for mobiles and tablets
**Earlier -** 
**Updated -**

Corrected the discord and telegram card for issue #642

---

src/components/ScrollToTop.jsx

This PR fixes the following issues: Overlapping of the scroll to top button
closes #issue-number #636
I have changed the tailwind css classes and fixed the issue
🔝for the mobile view
🔝for the desktop view

Update ScrollToTop.jsx as a fix of issue #636

---

src/content/Hackathons/napptive.js
src/pages/PerticularhackathonPage.jsx

conditional rendering the button and form

---

src/components/PageComp/IndividualWebinar/About.jsx
src/content/Webinars/GopherWebinar.js

Gopher fix

---

src/pages/MeetupPage.jsx

Meetup page fix

---

src/content/Webinars/index.content.js

Fix: Syntax error

---

src/content/Webinars/index.content.js

fix prettier issues in webinar index

---

src/content/Webinars/index.content.js

sort upcoming events display order

---

src/components/links/ButtonLink.jsx
src/pages/Super25Page.jsx

- Removes timelines from super25 page temporarily.
- Implements disabled property in the ButtonLink component.

update super25 page

---

src/pages/Super25Page.jsx

remove arrowlink from the application closed button in super25 page

---

src/content/Webinars/ZeroDowntimeKubeslice.js

Updated the webinar link and it's now past webinar

Add link for Zero RTO webinar

---

src/components/PageComp/IndividualWebinar/Register.jsx
src/content/Webinars/ChatOpsWebinar.js

- Fix typo mistake for "Register" word
- Add YT link for ChatOps Webinar

Add yt link for ChatOps Webinar and fix typo

---

src/content/Webinars/CostOptimizationWebinar.js

- Add YT link for Kubernetes Cost Saving webinar

Add YT link for Kubernetes Cost Saving webinar

---

src/pages/OpenSourceCoursePage.jsx

The original sentence in wemakedevs/src/pages/OpenSourceCoursePage.jsx contained an error, and this PR addresses and corrects that mistake. The fix ensures that the sentence is grammatically accurate and conveys the intended meaning properly.
Changed the sentence from "Who should you join this course? " to "Who should join the course"

Fix incorrect sentence in wemakedevs/src/pages/OpenSourceCoursePage.jsx/

---

src/pages/OpenSourceCoursePage.jsx

following are changes made to fix typos
1. `Course Strucure` should be `Course Structure`.
2. `exciting prices` should be `exciting prizes`.

Fixed some typos in OpenSourceCoursePage.jsx

---

src/pages/OpenSourceCoursePage.jsx

closes #699
- [x ] My code follows the code style of this project.
- [ x] The title of my pull request is a short description of the requested changes.

Fix Typos: OpenSourceCoursePage.js

---

src/components/PageComp/HashnodePage/Tracks.jsx

fix quote problem in hashnode page

---

src/content/Meetup/delhi-may-2023.js
src/content/Meetup/index.js
src/pages/ParticularMeetupPage.jsx

- Updated link of the main video for Delhi event meetup
- Replaced the video link at the bottom of the same page
- Added new URLs for some of the community partners redirecting to their respective websites.
- In the August meetup card, link to the button has been changed

Update links on meetup pages

---

src/content/courses/CoursesPageContent.js
src/content/courses/devops.js
src/content/courses/dsa.js
src/content/courses/gitGithub.js
src/content/courses/opensource.js
src/pages/content.js

- Fixes https://github.com/WeMakeDevs/wemakedevs/issues/726
- Typo in the words , words : `Socials`, `wining`, and `organzie` are changed to `Social`, `winning`, and `organize` respectively in Events , FAQ and in various files.
- "organize" word changed in Event Page, Hackathon Page, Scholarship page, and Educational Event Page.
- "Assignment" word changed in DevOps and DSA Pages.
- "winning!" word changed in Hashnode Page Content.
- "socials" word changed in Courses Page, DevOps, DSA, Git/Github, and Open Source sections.

Fixed Typo in  Home Page , Events , FAQ 

---

src/components/layout/Footer.jsx

- closes #716 
- Added colours of the logo of socials to the icons in the WeMakeDevs website's footer.
https://github.com/WeMakeDevs/wemakedevs/assets/105960032/25f645a4-97aa-4450-a75f-a55daaf53112

Added hover effects in Footer icons in the website

---

src/content/courses/devops.js
src/content/courses/dsa.js

Sorts the syllabus of DSA and DevOps course pages as per the playlist on YouTube.
closes #720
Sorted the order of DSA and DevOps course syllabus in `src/content/courses/dsa.js` and `src/content/courses/devops.js` respectively.
Sorted DSA Course Syllabus
Sorted DevOps Course Syllabus

sorted "dsa" and "devops" syllabus as per playlist

---

src/components/layout/Navbar/index.module.css

- Fix mobile menu not displaying correctly on landscape mode
| Before | After |
|:------:|:-----:|
| <img src="https://github.com/WeMakeDevs/wemakedevs/assets/52018183/bec984b1-82c6-4ccd-95ac-9145c0704cdf" width="300"> | <img src="https://github.com/WeMakeDevs/wemakedevs/assets/52018183/29c9088c-35bf-40a3-989b-5b3662c87b98" width="300"> |

fix: fix mobile menu layout for landscape mode

---

src/content/courses/opensource.js
src/pages/OpenSourceCoursePage.jsx

feat: remove register from open source course page

---

src/components/layout/Footer.jsx

feat: threads social to footer

---

src/pages/CoursesPage.jsx

 remove deleted testimonial from courses page

---

LICENSE

closes #744 
update copyright year in license file

update: copyright year

---

src/components/layout/JoinUs/NewsLetter.jsx

overflow-hidden

---

src/components/PageComp/IndividualWebinar/Register.jsx
src/components/layout/JoinUs/NewsLetter.jsx

Fix iframe height
